# Generated by Django 3.1.3 on 2020-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='rating',
            field=models.FloatField(default='1'),
        ),
    ]
