# Generated by Django 3.1.3 on 2020-11-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp1', '0002_destinations_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='image',
            field=models.TextField(default='Canada-Montreal'),
        ),
    ]
